-- Preserve the source's original time strings.  RSTGCN's September 2024
-- files provide times without an unambiguous timestamp/timezone, so these
-- columns retain that provenance rather than inventing a timestamp.
ALTER TABLE RAIL_DELAY_ANALYTICS.RAW.TRAIN_RUNNING_EVENTS
    ADD COLUMN IF NOT EXISTS SOURCE_SCHEDULED_ARRIVAL_TIME VARCHAR;

ALTER TABLE RAIL_DELAY_ANALYTICS.RAW.TRAIN_RUNNING_EVENTS
    ADD COLUMN IF NOT EXISTS SOURCE_ACTUAL_ARRIVAL_TIME VARCHAR;

ALTER TABLE RAIL_DELAY_ANALYTICS.RAW.TRAIN_RUNNING_EVENTS
    ADD COLUMN IF NOT EXISTS SOURCE_SCHEDULED_DEPARTURE_TIME VARCHAR;

ALTER TABLE RAIL_DELAY_ANALYTICS.RAW.TRAIN_RUNNING_EVENTS
    ADD COLUMN IF NOT EXISTS SOURCE_ACTUAL_DEPARTURE_TIME VARCHAR;
