-- Run once as ACCOUNTADMIN. The hosted dashboard never needs ACCOUNTADMIN.
CREATE ROLE IF NOT EXISTS RAIL_DELAY_DASHBOARD_READER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT USAGE ON DATABASE RAIL_DELAY_ANALYTICS TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT USAGE ON SCHEMA RAIL_DELAY_ANALYTICS.ANALYTICS TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT USAGE ON SCHEMA RAIL_DELAY_ANALYTICS.AUDIT TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT USAGE ON SCHEMA RAIL_DELAY_ANALYTICS.ML TO ROLE RAIL_DELAY_DASHBOARD_READER;

GRANT SELECT ON TABLE RAIL_DELAY_ANALYTICS.ANALYTICS.FACT_STATION_ARRIVAL TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT SELECT ON TABLE RAIL_DELAY_ANALYTICS.ANALYTICS.DIM_STATION TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT SELECT ON TABLE RAIL_DELAY_ANALYTICS.AUDIT.INGESTION_RUN_AUDIT TO ROLE RAIL_DELAY_DASHBOARD_READER;
GRANT SELECT ON TABLE RAIL_DELAY_ANALYTICS.ML.MODEL_EVALUATION_AUDIT TO ROLE RAIL_DELAY_DASHBOARD_READER;

-- Create a separate service user in Snowsight, assign this role, and set its password there.
-- Do not use the personal ACCOUNTADMIN account in a hosted service.
